import { getDb, cors } from '../../../_db.js';

export default async function handler(req, res) {
  cors(res);
  if (req.method === 'OPTIONS') return res.status(200).end();

  const db = getDb();
  const { id } = req.query;

  // GET /api/vendors/[id]/generate-config
  if (req.method !== 'GET') return res.status(405).json({ error: 'Method not allowed' });

  try {
    const [vendors] = await db.query('SELECT * FROM vendors WHERE id = ?', [id]);
    if (vendors.length === 0) return res.status(404).json({ error: 'Vendor not found' });

    const vendor = vendors[0];

    const envContent = `# ================================================================
# Restaurant POS Backend Configuration
# Generated by HappyPie SaaS Admin on ${new Date().toLocaleDateString('en-IN')}
# Restaurant: ${vendor.business_name}
# ================================================================

# 💻 Local Database (Zero-Config Embedded SQLite DB)
DB_HOST=localhost
IS_LOCAL=true

# 🏢 Multi-Tenant Identity — DO NOT CHANGE THIS
VENDOR_ID=${vendor.id}
VENDOR_SLUG=${vendor.slug}
VENDOR_NAME=${vendor.business_name}

# ☁️ Cloud Sync (Auto-sync orders/data to HappyPie cloud)
ENABLE_CLOUD_SYNC=true
CLOUD_DB_HOST=${process.env.CLOUD_DB_HOST || 'gateway01.ap-southeast-1.prod.aws.tidbcloud.com'}
CLOUD_DB_PORT=${process.env.CLOUD_DB_PORT || '4000'}
CLOUD_DB_USER=${process.env.CLOUD_DB_USER || ''}
CLOUD_DB_PASSWORD=${process.env.CLOUD_DB_PASSWORD || ''}
CLOUD_DB_NAME=${process.env.CLOUD_DB_NAME || 'pos_db'}
CLOUD_DB_SSL=true

# Server Port
PORT=5000
`;

    return res.status(200).json({
      success: true,
      vendor_id: vendor.id,
      vendor_name: vendor.business_name,
      vendor_slug: vendor.slug,
      env_content: envContent,
      setup_instructions: [
        `1. Download HappyPie Multi-Outlet ERP Setup.exe on the restaurant's computer`,
        `2. Double-click the installer to launch the 1-Click Installation Wizard`,
        `3. Open POS App Settings and paste VENDOR_ID=${vendor.id} (or save the .env file in app userData directory)`,
        `4. Local SQLite Database & UDP Auto-Discovery start automatically on Port 5000`,
        `5. Android TV KDS and Waiter Mobiles will auto-pair immediately on local Wi-Fi`,
      ]
    });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
}
