import { getDb, cors } from '../_db.js';
import crypto from 'crypto';
import { getActivationTokenSecret, requireSaasAdminAuth } from '../_auth.js';

function generateActivationToken(vendorId, vendorCode) {
  const secret = getActivationTokenSecret();
  const expiresAt = Date.now() + 7 * 24 * 60 * 60 * 1000;
  const payload = Buffer.from(JSON.stringify({ vendorId, vendorCode, expiresAt })).toString('base64url');
  const sig = crypto.createHmac('sha256', secret).update(payload).digest('base64url');
  return `${payload}.${sig}`;
}

export default async function handler(req, res) {
  cors(res);
  if (req.method === 'OPTIONS') return res.status(200).end();

  const admin = requireSaasAdminAuth(req, res);
  if (!admin) return;

  const db = getDb();
  const { vendor_id } = req.query;

  try {
    const [vendors] = await db.query('SELECT * FROM vendors WHERE id = ?', [vendor_id]);
    if (vendors.length === 0) return res.status(404).json({ error: 'Vendor not found' });
    const vendor = vendors[0];
    const vendorCode = vendor.vendor_code || `HP-VEN-${vendor.id}`;
    const activationToken = generateActivationToken(vendor.id, vendorCode);

    return res.status(200).json({
      success: true,
      vendor_id: vendor.id,
      vendor_name: vendor.business_name,
      vendor_slug: vendor.slug,
      vendor_code: vendorCode,
      activation_token: activationToken,
      expires_in_days: 7,
      setup_instructions: [
        `1. Download HappyPie Multi-Outlet ERP Setup.exe on the restaurant's computer`,
        `2. Launch the POS app and open the Setup Wizard`,
        `3. Paste the activation token generated by SaaS Admin`,
        `4. The POS will verify with SaaS Admin Cloud and save local offline config`,
        `5. Do not copy cloud database credentials or .env files to client machines`,
      ]
    });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
}
